/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Conexion.DataBase;
import Modelos.ListaVer;
import Modelos.RenderTabla;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author AGIL
 */
public class VerDetalles extends javax.swing.JDialog {
    public int id_usuario;
    public int id_empresa;
    public int idVenta;
    public DataBase db = new DataBase();
    private  List<ListaVer> listaVenta = new ArrayList<>();
    private List<ListaVer> ListaDetalles = new ArrayList<>();
    public DefaultTableModel modelTabla;
    /**
     * Creates new form VerDetalles
     */
    public VerDetalles(java.awt.Frame parent, boolean modal,int id_usuario,int id_empresa,int idVenta) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        this.id_usuario = id_usuario;
        this.id_empresa = id_empresa;
        this.idVenta = idVenta;
        
        modelTabla = (DefaultTableModel)tablaDetalles.getModel();
        //tablaDetalles.setDefaultRenderer(Object.class, new RenderTabla());
        tablaDetalles.getTableHeader().setPreferredSize(new java.awt.Dimension(0, 33));
        tablaDetalles.getTableHeader().setBackground(Color.cyan);
        tablaDetalles.getTableHeader().setForeground(Color.blue);
        tablaDetalles.setRowHeight(33);
        centrar_datos();
        alinearTextoTabla();
        GenerarDatos();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void centrar_datos(){  
        DefaultTableCellRenderer modelocentrar = new DefaultTableCellRenderer(); 
        modelocentrar.setHorizontalAlignment(SwingConstants.CENTER); 
        tablaDetalles.getColumnModel().getColumn(1).setCellRenderer(modelocentrar); 
        tablaDetalles.getColumnModel().getColumn(2).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(3).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(4).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(5).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(6).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(7).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(8).setCellRenderer(modelocentrar);   
        tablaDetalles.getColumnModel().getColumn(9).setCellRenderer(modelocentrar);
        tablaDetalles.getColumnModel().getColumn(10).setCellRenderer(modelocentrar);
    } 
        
    public void alinearTextoTabla(){
        TableCellRenderer rendererFromHeader = tablaDetalles.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
    }
        
    public void GenerarDatos(){
        ResultSet rs = null;
        ResultSet rs1 = null;
        int idVenta = 0;
       
        String consulta = "SELECT RS.RAZON_SOCIAL,RS.NIT,V.FACTURA,V.AUTORIZACION ,V.FECHA,V.CODIGO_CONTROL,S.NOMBRE,A.NOMBRE,TP.NOMBRE,V.PAGADO,V.CAMBIO, V.ID \n" +
        "FROM INV_VENTA AS V \n" +
        "INNER JOIN INV_MOVIMIENTO AS M ON  M.ID = V.MOVIMIENTO\n" +
        "INNER JOIN ALMACEN AS A ON A.ID = V.ALMACEN\n" +
        "LEFT JOIN SUCURSAL AS S ON S.ID = A.SUCURSAL\n" +
        "LEFT JOIN CLIENTE AS RS ON RS.ID = INTEGER(V.CLIENTE)\n" +
        "LEFT JOIN CLASE AS TP ON TP.ID = V.TIPO_PAGO\n" +
        "WHERE S.EMPRESA = "+this.id_empresa+" AND V.ID = "+this.idVenta;
        rs = db.seleccionar(consulta);
        try {
            while (rs.next()) {                
                String razonSocial = rs.getString(1);
                int nit = rs.getInt(2);
                int factura = rs.getInt(3);
                String autorizacion = rs.getString(4);
                String fecha = rs.getString(5);
                String codigoControl = rs.getString(6);
                String sucursal = rs.getString(7);
                String almacen = rs.getString(8);
                String tipoPago = rs.getString(9);
                double pago = rs.getDouble(10);
                double cambio = rs.getDouble(11);
                idVenta = rs.getInt(12);

                ListaVer ventas = new ListaVer(idVenta, nit, razonSocial, factura, autorizacion, fecha, codigoControl, sucursal, almacen, tipoPago, pago, cambio);
                listaVenta.add(ventas);
            }
            
            
            
            String consultadv = "select P.NOMBRE, P.CODIGO,P.UNIDAD_MEDIDA,P.PRECIO_UNITARIO,DV.CANTIDAD,DV.IMPORTE,DV.DESCUENTO,DV.RECARGO,DV.ICE,DV.EXCENTO,DV.TOTAL\n" +
                "from INV_DETALLE_VENTA as DV\n" +
                "inner join PRODUCTO as P on P.IDP = DV.PRODUCTO\n" +
                "inner join INV_VENTA as V on V.ID = DV.VENTA\n" +
                "where V.ID = "+idVenta+" AND P.ALMACEN = V.ALMACEN";
            rs1 = db.seleccionar(consultadv);
            while (rs1.next()) {                
                String nombre = rs1.getString(1);
                String codigo = rs1.getString(2);
                String unidaMedida = rs1.getString(3);
                double precioUnit = rs1.getDouble(4);
                double cantidad = rs1.getDouble(5);
                double importe = rs1.getDouble(6);
                double descuento = rs1.getDouble(7);
                double recargos = rs1.getDouble(8);
                double ice = rs1.getDouble(9);
                double excento = rs1.getDouble(10);
                double sujetoAdj = rs1.getDouble(11);
                
                ListaVer detallesV = new ListaVer(nombre, codigo, unidaMedida, precioUnit, cantidad, importe, descuento, recargos, ice, excento, sujetoAdj);
                ListaDetalles.add(detallesV);
            }
            
        } catch (Exception e) {
            System.out.println("Error al obtener los datos en pantalla venta: "+e);
        }
    }
    
    public void mostrarDatos(){
        
        for (ListaVer ventaLista : listaVenta) {
            int nit = ventaLista.getNit();
            labelNit.setText(Integer.toString(nit));
            String razonSocial = ventaLista.getRazon_social();
            labelRazonSocial.setText(razonSocial);
            int factura = ventaLista.getNumFactura();
            labelNumFactura.setText(Integer.toString(factura));
            String autorizacion = ventaLista.getNumAutorizacion();
            labelAutorizacion.setText(autorizacion);
            String fecha = ventaLista.getFecha();
            labelFecha.setText(fecha);
            String codigoControl = ventaLista.getCodigoControl();
            labelCodigoControl.setText(codigoControl);
            String tipoPago = ventaLista.getTipoPago();
            labelTipago.setText(tipoPago);
            double pago = ventaLista.getPago();
            labelPago.setText(Double.toString(pago));
            double cambio = ventaLista.getCambio();
            labelCambio.setText(Double.toString(cambio));
            
        }
        double total = 0;
        for (ListaVer ListaDetalles : ListaDetalles) {
            String nombre = ListaDetalles.getNombreProducto();
            String codigo = ListaDetalles.getCodigoItem();
            String unidMed = ListaDetalles.getUnidadMedida();
            double precioUnit = ListaDetalles.getPrecioUnitario();
            double cantidad = ListaDetalles.getCantidad();
            double importe = ListaDetalles.getImporte();
            double descuento = ListaDetalles.getDescuento();
            double recargos = ListaDetalles.getRecargos();
            double ice = ListaDetalles.getIce();
            double excento = ListaDetalles.getExcentos();
            double sujetoA = precioUnit * cantidad;
            total = total + sujetoA;
            Object[] datos = {nombre,codigo,unidMed,precioUnit,cantidad,importe,descuento,recargos,ice,excento,sujetoA};
            modelTabla.addRow(datos);
            tablaDetalles.setModel(modelTabla);
        }
        labelTotal.setText(Double.toString(total));
        
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        labelNit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelRazonSocial = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNumFactura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        labelAutorizacion = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        labelCodigoControl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        labelTipago = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelCambio = new javax.swing.JLabel();
        labelPago = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 159, 199));
        jLabel1.setText("DATOS DE VENTA");

        jButton1.setBackground(new java.awt.Color(183, 70, 53));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("NIT:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("RAZÓN SOCIAL:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("NÚM. FACTURA:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("NÚM. AUTORIZACIÓN:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("FECHA:");
        jLabel4.setPreferredSize(new java.awt.Dimension(85, 14));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CÓGIDO DE CONTROL:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("TIPO DE PAGO:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PAGO:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("CAMBIO:");
        jLabel11.setPreferredSize(new java.awt.Dimension(85, 14));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 159, 199));
        jLabel6.setText("DETALLE DE LA VENTA");

        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Código Item", "<html>Unidad <br>De Medida</html>", "<html>Precio Unitario<br>(Bs/u)</html>", "<html>Cantidad <br>(u)</html>", "<html>Importe <br>(Bs)</html>", "<html>Descuentos<br> (-)</html>", "<html>Recargos <br>(+)</html>", "<html>Ice <br>(-)</html>", "<html>Excentos <br>(-)</html>", "Sujeto a DF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalles.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(tablaDetalles);

        jLabel12.setText("Total:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jSeparator5)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(labelTipago, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelNit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jLabel3)
                                .addGap(30, 30, 30)
                                .addComponent(labelRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel5)
                                .addGap(59, 59, 59)
                                .addComponent(labelNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelAutorizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)
                                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(103, 103, 103)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelCodigoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(labelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(35, 35, 35)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(labelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 60, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelNit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNumFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelRazonSocial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelAutorizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCodigoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(labelTipago, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(labelCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelAutorizacion;
    private javax.swing.JLabel labelCambio;
    private javax.swing.JLabel labelCodigoControl;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNit;
    private javax.swing.JLabel labelNumFactura;
    private javax.swing.JLabel labelPago;
    private javax.swing.JLabel labelRazonSocial;
    private javax.swing.JLabel labelTipago;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JTable tablaDetalles;
    // End of variables declaration//GEN-END:variables
}
