/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PanelUI;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Database;

/**
 *
 * @author AGIL
 */
public class Compras extends javax.swing.JFrame {
    public int id_usuario;
    public Database db = new Database();
    /**
     * Creates new form Compras
     */
    public Compras(int id_usuario) {
        initComponents();
        setTitle("Compras");
        setLocationRelativeTo(this);
        
        this.id_usuario = id_usuario;
        obtenerSucursal();
    }
    
    public String obtenerSucursal(){
        ResultSet rs = null;
        String sucursal = "";
        int idEmpresa = obtenerIdEmpresa();
        String consulta = "SELECT NOMBRE \n" +
            "FROM SUCURSAL\n" +
            "WHERE EMPRESA = "+idEmpresa;
        try{
            rs = db.seleccionar(consulta);
            while (rs.next()) {                
                sucursal = rs.getString(1);
                comboSucursal.addItem(sucursal);
            }
        }catch(Exception e){
            System.out.println("Error al mostrar las sucursales: "+e.getMessage());
        }finally{
            try {
                rs.close();
                db.Conectar().close();
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return sucursal;
    }
    
    public int obtenerIdEmpresa(){
        ResultSet rs = null;
        int id = 0;
        try{
            rs = db.seleccionar("SELECT EMPRESA FROM USUARIO WHERE ID = "+this.id_usuario);
            while(rs.next()){
                id = rs.getInt(1);
            }
        }catch(Exception e){
            System.out.println("Error al seleccion el id empresa: "+e.getMessage());
        }finally{
            try {
                rs.close();
                db.Conectar().close();
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return id ;
    }
    
    public int obtenerIdTipoPago(String tipoPago){
        ResultSet rs = null;
        int id = 0;
        String consulta = "SELECT ID\n" +
            "FROM CLASE \n" +
            "WHERE ID_TIPO = "+36+" AND NOMBRE = '"+tipoPago+"'";
        try{
            rs = db.seleccionar(consulta);
            while(rs.next()){
                id = rs.getInt(1);
            }
        }catch(Exception e){
            try {
                rs.close();
                db.Conectar().close();
            } catch (SQLException ex) {
                Logger.getLogger(Compras.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return id;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboTipoPago = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jfechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jfechaHasta = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textoRazonSocial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboSucursal = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textoNit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textoMonto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        comboTipoCompra = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnFiltro = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comboTipoPago.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 143, 202));
        jLabel1.setText("COMPRAS");

        jSeparator1.setForeground(new java.awt.Color(71, 143, 202));

        btnNuevo.setBackground(new java.awt.Color(27, 106, 170));
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/addition-white.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(71, 143, 202)));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 143, 202));
        jLabel2.setText("Filtro de Compras");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(71, 143, 202));
        jLabel3.setText("Periodo");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(71, 143, 202));
        jLabel4.setText("Desde");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(71, 143, 202));
        jLabel5.setText("Hasta");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(71, 143, 202));
        jLabel6.setText("Filtro");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(71, 143, 202));
        jLabel7.setText("Razón Social");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(71, 143, 202));
        jLabel11.setText("Sucursal");

        comboSucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(71, 143, 202));
        jLabel12.setText("Usuario");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(71, 143, 202));
        jLabel8.setText("Nit");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(71, 143, 202));
        jLabel9.setText("Monto");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(71, 143, 202));
        jLabel10.setText("Tipo de Compra");

        comboTipoCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "TODOS", "CONTADO", "CREDITO" }));

        jPanel2.setBackground(new java.awt.Color(71, 143, 202));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Lista de Compras");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Sucursal", "<html><center>Razón Social<br>Proveedor</center></html>", "Nit Proveedor", "Factura", "<html><center>Fecha<br>Facturada</center></html>", "Hora-Fecha", "Monto", "Tipo de Monto", "Pago", "Usuario"
            }
        ));
        jTable2.setFillsViewportHeight(true);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(30);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        btnFiltro.setText("Filtrar");
        btnFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout comboTipoPagoLayout = new javax.swing.GroupLayout(comboTipoPago);
        comboTipoPago.setLayout(comboTipoPagoLayout);
        comboTipoPagoLayout.setHorizontalGroup(
            comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(comboTipoPagoLayout.createSequentialGroup()
                        .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel7)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel8)
                                .addGap(118, 118, 118)
                                .addComponent(jLabel9)
                                .addGap(84, 84, 84)
                                .addComponent(jLabel10))
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                        .addComponent(comboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                        .addComponent(textoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addComponent(textoNit, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31)
                                .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(comboTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel11)
                                .addGap(114, 114, 114)
                                .addComponent(jLabel12))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(comboTipoPagoLayout.createSequentialGroup()
                        .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jLabel4)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel5))
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(41, 41, 41)
                                .addComponent(jfechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jfechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFiltro)
                        .addGap(63, 63, 63)))
                .addContainerGap())
        );
        comboTipoPagoLayout.setVerticalGroup(
            comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfechaDesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboTipoPagoLayout.createSequentialGroup()
                        .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addGroup(comboTipoPagoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jfechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboTipoPagoLayout.createSequentialGroup()
                        .addComponent(btnFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, comboTipoPagoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(9, 9, 9)))
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(comboTipoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(comboTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        NuevaCompra nuevaCompra = new NuevaCompra(this, true,this.id_usuario);
        nuevaCompra.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltroActionPerformed
        Date feD = this.jfechaDesde.getDate();
        Date feH = this.jfechaHasta.getDate();
        String razon_social = textoRazonSocial.getText();
        ResultSet rs = null;
        String consultaRazonSocial = "";
        String consultaNit = "";
        String textoNit = this.textoNit.getText();
        String textoMonto = this.textoMonto.getText();
        String consultaMonto = "";
        String textoTipoPago = (String)comboTipoCompra.getSelectedItem();
        String consultaTipoPago = "";
        String textoUsuario = this.textoUsuario.getText();
        String consultaUsuario = "";
        
        try{
            if(!feD.toString().isEmpty() && !feH.toString().isEmpty()){
   
                long f1 = feD.getTime();
                java.sql.Date desde = new java.sql.Date(f1);
                long f2 = feH.getTime();
                java.sql.Date hasta = new java.sql.Date(f2);
                
                if(!razon_social.equals("")){
                    consultaRazonSocial = "AND P.RAZON_SOCIAL = '"+razon_social+"'";
                }
                if(!textoNit.equals("")){
                    consultaNit = "AND P.NIT = '"+textoNit+"'";
                }
                if (!textoMonto.equals("")) {
                    consultaMonto = "AND C.TOTAL = "+textoMonto;
                }
                if (!textoTipoPago.equals("")) {
                    if (textoTipoPago.equals("TODOS")) {
                        consultaTipoPago = "";
                    }else{
                        int idTipoPago = obtenerIdTipoPago(textoTipoPago);
                        consultaTipoPago = "AND C.TIPO_PAGO = "+idTipoPago;
                    }                   
                }
                if (textoUsuario.equals("")) {
                    consultaUsuario = "AND U.NOMBRE_USUARIO = '"+textoUsuario+"'";
                }
                
                String consulta = "SELECT S.NOMBRE, P.RAZON_SOCIAL, P.NIT, C.FACTURA, C.FECHA, C.TOTAL, C.TIPO_PAGO, C.DIAS_CREDITO,C.A_CUENTA, U.NOMBRE_USUARIO\n" +
                "FROM COMPRA AS C\n" +
                "INNER JOIN ALMACEN AS A ON C.ALMACEN = A.ID\n" +
                "INNER JOIN SUCURSAL AS S ON S.ID = A.SUCURSAL\n" +
                "INNER JOIN PROVEEDOR AS P ON P.ID = C.PROVEEDOR\n" +
                "INNER JOIN USUARIO AS U ON U.ID = C.USUARIO\n" +
                "INNER JOIN CLASE AS TP ON TP.ID = C.TIPO_PAGO\n" +
                "WHERE C.FECHA >= '"+desde+"' AND C.FECHA <= '"+hasta+"'"+consultaNit+" "+consultaRazonSocial+""
                +" "+consultaMonto+" "+consultaTipoPago+" "+consultaUsuario;
                
                rs = db.seleccionar(consulta);
               while(rs.next()){
                   String almacen = rs.getString(1);
                   String proveedor = rs.getString(2);
                   int nit = rs.getInt(3);
                   java.math.BigDecimal factura = rs.getBigDecimal(4);
                   String fecha = rs.getString(5);
                   double monto = rs.getDouble(6);
                   String tipoPago = rs.getString(7);  
               }
                         
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese las fechas.");
        }
        
    }//GEN-LAST:event_btnFiltroActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltro;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> comboSucursal;
    private javax.swing.JComboBox<String> comboTipoCompra;
    private javax.swing.JPanel comboTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jfechaDesde;
    private com.toedter.calendar.JDateChooser jfechaHasta;
    private javax.swing.JTextField textoMonto;
    private javax.swing.JTextField textoNit;
    private javax.swing.JTextField textoRazonSocial;
    private javax.swing.JTextField textoUsuario;
    // End of variables declaration//GEN-END:variables
}
