module.exports=function(){
	var Diccionario={
		EGRE_FACTURACION:"FACT",
		EGRE_PRE_FACTURACION:"PREFACT",
		EGRE_BAJA:"BAJA",
		EGRE_PROFORMA:"PFR",
		EGRE_TRASPASO:"TRAS",
		EGRE_AJUSTE:"AJU",
		MOV_ING:"MOVING",
		MOV_EGRE:"MOVEGR",
		ING_TRASPASO:"IPT",
		ROL_VENDEDOR:"VENDEDOR",
		TIPO_PRODUCTO_BASE:"PBASE",
		TIPO_PRODUCTO_INTERMEDIO:"PINTER",
		TIPO_PAGO_CREDITO:"CRE",
		ING_POR_INVENTARIO:"III",
		DESTINO_CIERRE_SIGUIENTETURNO:"SIGUIENTETURNO",
		TIPOS_CUENTA_CONTABILIDAD:"TCC",
		PRE_REQUSITO:"MLPR",
		GENERO:"GNR",
		IVA_DF:"IVA DF",
		IVA_CF:"IVA CF",
		IT:"IT",
		IT_POR_PAGAR:"IT POR PAGAR",
		CAJA_BANCOS:"CAJA/BANCOS",
		ROL_ADMINISTRADOR:"ADMINISTRADOR",
		TIPOCONTROL:"TCMP",
		CORRECTIVO:"CORR",
		PREVENTIVO:"PRE",
		RUTINA:"RUT",
		ENTREGA:"ENT"
	}
	return Diccionario;
}