ALTER TABLE agil_rrhh_empleado_historial_vacacion add ficha  int(11);
ALTER TABLE agil_rrhh_empleado_historial_vacacion DROP FOREIGN KEY agil_rrhh_empleado_historial_vacacion_ibfk_1;
ALTER TABLE agil_rrhh_empleado_historial_vacacion drop empleado;
ALTER TABLE agil_rrhh_empleado_historial_vacacion ADD CONSTRAINT agil_rrhh_empleado_historial_vacacion_ibfk_1 FOREIGN KEY (ficha) REFERENCES agil_rrhh_empleado_ficha (id);
