ALTER TABLE inv_cotizacion DROP estado;
ALTER TABLE inv_cotizacion DROP plazo;
ALTER TABLE inv_cotizacion DROP nota;
ALTER TABLE inv_cotizacion DROP observacion;
ALTER TABLE inv_cotizacion DROP firma;
ALTER TABLE inv_cotizacion DROP cargo;
ALTER TABLE inv_cotizacion DROP fecha_estado;
ALTER TABLE inv_cotizacion DROP cliente;
ALTER TABLE inv_cotizacion DROP almacen;
ALTER TABLE inv_cotizacion DROP FOREIGN KEY inv_cotizacion_ibfk_2;
ALTER TABLE inv_cotizacion DROP FOREIGN KEY inv_cotizacion_ibfk_3;