
ALTER TABLE agil_configuracion_general_factura DROP formato_color_nota_venta;
ALTER TABLE agil_configuracion_general_factura DROP formato_papel_nota_baja;
ALTER TABLE agil_configuracion_general_factura DROP nota_factura_nota_baja;
ALTER TABLE agil_configuracion_general_factura DROP color_cabecera_nota_baja;
ALTER TABLE agil_configuracion_general_factura DROP color_detalle_nota_baja;
ALTER TABLE agil_configuracion_general_factura DROP tipo_configuracion_nota_baja;

ALTER TABLE agil_configuracion_factura DROP formato_color_nota_baja;
ALTER TABLE agil_configuracion_factura DROP formato_papel_nota_baja;
ALTER TABLE agil_configuracion_factura DROP nota_factura_nota_baja;
ALTER TABLE agil_configuracion_factura DROP color_cabecera_nota_baja;
ALTER TABLE agil_configuracion_factura DROP color_detalle_nota_baja;
ALTER TABLE agil_configuracion_factura DROP tipo_configuracion_nota_baja;